language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t meanthe/docker-full -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true meanthe/docker-full npm run test

after_success:
  - docker build -t Taekyun/docker-frontend ./frontend
  - docker build -t Taekyun/docker-backend ./backend
  - docker build -t Taekyun/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push Taekyun/docker-frontend
  - docker push Taekyun/docker-backend
  - docker push Taekyun/docker-nginx
